version: '3.3'

volumes:
  pg_data:
  static_volume:
  media:


services:

  db_django:
    container_name: calculator_db_django
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  calculator:
    build: ./calculator/
    env_file: .env
    depends_on:
      - db_django
    volumes:
      - static_volume:/staticfiles
      - media:/media
  nginx:
    build: ./nginx/
    depends_on:
      - calculator
    volumes:
      - static_volume:/staticfiles
      - media:/media
    ports:
      - 8000:80
