# Generated by Django 4.2.7 on 2023-12-15 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_hanging', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Отечественный-подвесные')),
                ('national_crown', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Отечественный-навершие')),
                ('national_gift', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Отечественный-подарки')),
                ('national_garland', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Отечественный-гирлянды')),
                ('eastern_hanging', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Восточный-подвесные')),
                ('eastern_crown', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Восточный-навершие')),
                ('eastern_gift', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Восточный-подарки')),
                ('eastern_garland', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Восточный-гирлянды')),
                ('magic_hanging', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Сказочный-подвесные')),
                ('magic_crown', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Сказочный-навершие')),
                ('magic_gift', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Сказочный-подарки')),
                ('magic_garland', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Сказочный-гирлянды')),
                ('christmas_hanging', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Рождественский-подвесные')),
                ('christmas_crown', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Рождественский-навершие')),
                ('christmas_gift', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Рождественский-подарки')),
                ('christmas_garland', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Рождественский-гирлянды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ('-created_at',),
            },
        ),
    ]
