# Generated by Django 4.2.7 on 2023-12-21 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', models.BooleanField(default=True, verbose_name='Отечественный')),
                ('eastern', models.BooleanField(default=True, verbose_name='Восточный')),
                ('magic', models.BooleanField(default=True, verbose_name='Сказочный')),
                ('christmas', models.BooleanField(default=True, verbose_name='Рождество')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
