# Generated by Django 4.2.7 on 2023-12-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumselect',
            name='toggle',
            field=models.BooleanField(default=False, verbose_name='Переключатель'),
        ),
    ]
